services:
  mongo:
    image: mongo:latest
    container_name: mongo-track-wise
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: track-wise
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/mongo
    command: ["--auth"]

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: node-track-wise
    environment:
      DB_HOST: mongo
      DB_NAME: track-wise
      DB_USER: root
      DB_PASSWORD: root
      NODE_ENV: development
      PORT: 5001
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server

  # client:
  #   build:
  #     context: .
  #     dockerfile: client/Dockerfile
  #   container_name: react-track-wise
  #   environment:
  #     REACT_APP_API_URL: http://localhost:5001
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/app/client
  #     # leaving node_modules from the container
  #     - /app/client/node_modules

volumes:
  mongodb_data:
